.PHONY: typeset

typeset:
	pandoc                          \
	  --from         markdown       \
	  --to           latex          \
	  --template     template.tex   \
	  --out          assignment.pdf \
	  --pdf-engine   xelatex        \
	  assignment.md
