#!/usr/bin/env bash
FILES=($( cat index.txt ))

pandoc                        \
  --from         markdown     \
  --to           latex        \
  --template     template.tex \
  --out          report.pdf   \
  --latex-engine xelatex      \
  "${FILES[@]}"
